language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: AGJqrmS7CJUURWy28u2TGUwUNnTGPFL0Zkj+2CihW5UOsTg7EccCfST2MKMsiak8gk7stW5u2XWSYKQRIOiFVeDD7cst+5BVtcWjF9p/FPMTOWvT4GTzqbAWYBzq7lm2nPKirZQUNALSOrVQnacgOEQsRUHWPQpUcQk7H5OhdMJCnmrcR6fGwRt6co6FaFwF21jWy9wpC4Voyzm3vgQYO4191uX0FFEvhSXwpXsmqTfpLlLmd+V0gdCyOOLxsZuibN/ZO2IrTdQMFlq8jglMuC/4WPFfvWeogepSFdPZM40NYhQvYiGl8DKxo8d8kj3uk2XJwBkBuIJPE/Jcc6a74sAm5VaA5LdcMmViamE3YCtuqj9l2ggHcoYov5qoML3y0+RsNrne/QrWHqf0VIUAACoNOuzBxO9d9rUYRhKf2SegVBvFZburbJOyM3OfYhlYpgPunfrK4+bj8ZuCgULWAc2G6nR8Wlz882LzyrIyXm/8RUhhV4qw+XqjNJBZ6pqo6JPamsY2vS5jqaOnVIqwopHY/TFRuHGhBaKbS0XTEefWd2evxMGmYZGS1cv+/NCvkstFxmbQcuA36KrcZ/CMPmOsT6LMTIFHRtIrrOigQ/OxGFk6t516LtQv22o4QcmsjCGkZIIk0Zv2LPOMpqM+0vqqFwUDzWLuE3Ix4oGQfiI=
  app: stark-woodland-22950
  on:
    repo: brianlpham21/beer-application
